name: Greeting Workflow
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # This "downloads" your repo onto the runner
      
      - name: Run Python Tests
        run: python3 test_calc.py  # This executes your test file
